services:
  - type: web
    name: rms-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://rms-back-r2ox.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
